title: HarperPages
description: Books by Jack Harper
url: "https://jackharperbooks.github.io"
baseurl: "/harperpages"


# Collections
collections:
  books:
    output: true
    permalink: /books/:title/

# Build settings
markdown: kramdown
theme: minima # temporary; we’ll override with custom layouts
